name: Build AppImage for XIVLauncher-RB

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.gitlab.steamos.cloud/proton/sniper/sdk
    env:
      APP_VERSION: rb-v1.3.1.1-beta4
      APP_RELEASE: 1
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          apt update && apt install -y \
            file \
            wget \
            curl \
            unzip \
            zsync \
            fuse3 \
            libjxr0 \
            libsdl3-0 \
            libsecret-1-0 \
            libicu-dev \
            dpkg-dev \
            pcregrep
          ./create-basedir.sh
          ./copy-tools.sh
          ./copy-deps.sh
          ./copy-xivlauncher.sh
          ./make-appimage.sh
      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: xivlauncher-rb
          path: build/output
